name: check-gh-secret
on:
  workflow_call:
    inputs:
      gh-secret:
        description: 'Github secret'
        required: true
        type: string
jobs:
  check:
    name: ✅ Check Github secret ${{ inputs.gh-secret }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Github secret ${{ inputs.gh-secret }} presence
        env:
          GH_SECRET: ${{ inputs.gh-secret }}
        run: |
          if [ -z "${{ secrets[format('{0}', env.GH_SECRET)] }}" ]; then
            echo "Github secret ${{ env.GH_SECRET }} is missing."
            exit 1
          else
            echo "Github secret ${{ env.GH_SECRET }} is present."
          fi
