## TO FIX

name: check-gh-variables
on:
  workflow_call:
    inputs:
      gh-vars:
        default: "[]"
        required: false
        type: string
jobs:
  check:
    name: Check Github variables
    runs-on: ubuntu-latest
    steps:
      - name: Check Github variables
        uses: actions/github-script@v4
        with:
          script: |
            const envVars = ${{ toJson(inputs.gh-vars) }};
            const missingEnvVars = Object.keys(envVars).filter(key => !envVars[key]);
            if (missingEnvVars.length) {
              const errorMessage = Variables are not defined : ${missingEnvVars.join(', ')}`;
              throw new Error(errorMessage);
            }